apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: salonsaas.org
spec:
  secretName: salonsaas.org-prod
  dnsNames:
    - api.salonsaas.org
    - auth.salonsaas.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer