spring:
  application:
    name: @project.artifactId@
  web:
    resources:
      static-locations: file:ui/, classpath:/static/
  modulith:
    events:
      mongodb:
        transaction-management:
          enabled: true
  mongodb:
    representation:
      uuid: standard
