spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:postgresql://localhost:5432/saloon
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true