replicaCount: 1

hpa:
  enabled: false

ingress:
  host: auth.salonsaas.org

env:
  IDENTITY_SERVICE_URL: "https://api.salonsaas.org"

secret:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.salon.svc.cluster.local:5432/salon"
  SPRING_DATASOURCE_USERNAME: "postgres"
