package net.samitkumar.multi_tenant_salon.salon.internal;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
class SalonPolicyService {
    private final JdbcClient jdbc;
    private final ObjectMapper json;

    SalonPolicyService(JdbcClient jdbc, ObjectMapper json) { this.jdbc = jdbc; this.json = json; }

    List<SalonPolicy> defaults() {
        return List.of(
                template("privacy", "Privacy Policy",
                        "We use the information you provide, such as your contact and appointment details, to answer enquiries, arrange and provide salon services, communicate with you and keep required business records. We may share relevant information with service providers supporting the salon and where required by law. We keep information only as long as needed for these purposes and applicable record-keeping rules. Privacy rights depend on your location and may include access, correction or deletion. Contact the salon using the details on this website or your booking confirmation for questions or requests. The salon can provide details of its specific data practices.",
                        "Vi bruger de oplysninger, du giver os, såsom kontakt- og aftaleoplysninger, til at besvare henvendelser, arrangere og levere salonydelser, kommunikere med dig og opbevare lovpligtige virksomhedsregistre. Relevante oplysninger kan deles med tjenesteudbydere, der hjælper salonen, og når loven kræver det. Vi opbevarer kun oplysninger så længe, det er nødvendigt til disse formål og efter gældende opbevaringsregler. Dine databeskyttelsesrettigheder afhænger af, hvor du bor, og kan omfatte indsigt, rettelse eller sletning. Kontakt salonen via oplysningerne på hjemmesiden eller din bookingbekræftelse. Salonen kan give flere oplysninger om sin konkrete databehandling.",
                        "Vi använder uppgifter som du lämnar, till exempel kontakt- och bokningsuppgifter, för att besvara frågor, ordna och utföra salongstjänster, kommunicera med dig och spara nödvändiga verksamhetsunderlag. Relevanta uppgifter kan delas med tjänsteleverantörer som hjälper salongen och när lagen kräver det. Vi sparar uppgifter bara så länge det behövs för dessa ändamål och enligt gällande krav på arkivering. Dina dataskyddsrättigheter beror på var du bor och kan omfatta tillgång, rättelse eller radering. Kontakta salongen via uppgifterna på webbplatsen eller i din bokningsbekräftelse. Salongen kan ge mer information om sin specifika behandling av uppgifter.",
                        "Vi bruker opplysninger du gir oss, for eksempel kontakt- og bestillingsopplysninger, til å svare på henvendelser, ordne og utføre salongtjenester, kommunisere med deg og føre nødvendige virksomhetsregistre. Relevante opplysninger kan deles med tjenesteleverandører som bistår salongen, og når loven krever det. Vi oppbevarer opplysninger bare så lenge det er nødvendig for disse formålene og etter gjeldende krav til oppbevaring. Personvernrettighetene dine avhenger av hvor du bor, og kan omfatte innsyn, retting eller sletting. Kontakt salongen via opplysningene på nettstedet eller i bestillingsbekreftelsen. Salongen kan gi flere opplysninger om sin konkrete behandling av personopplysninger.",
                        "Nous utilisons les informations que vous nous communiquez, telles que vos coordonnées et les détails de votre rendez-vous, pour répondre à vos demandes, organiser et fournir les services du salon, communiquer avec vous et tenir les registres professionnels requis. Les informations pertinentes peuvent être partagées avec les prestataires qui assistent le salon et lorsque la loi l’exige. Nous les conservons uniquement pendant la durée nécessaire à ces fins et aux obligations de conservation applicables. Vos droits en matière de données dépendent de votre lieu de résidence et peuvent inclure l’accès, la rectification ou l’effacement. Contactez le salon aux coordonnées indiquées sur ce site ou dans votre confirmation de réservation pour toute question ou demande. Le salon peut fournir des précisions sur ses pratiques.",
                        "Wir verwenden die von Ihnen bereitgestellten Angaben, etwa Kontakt- und Termindaten, um Anfragen zu beantworten, Salonleistungen zu vereinbaren und zu erbringen, mit Ihnen zu kommunizieren und erforderliche Geschäftsunterlagen zu führen. Relevante Angaben können an Dienstleister weitergegeben werden, die den Salon unterstützen, sowie wenn dies gesetzlich vorgeschrieben ist. Wir speichern Angaben nur so lange, wie es für diese Zwecke und geltende Aufbewahrungspflichten erforderlich ist. Ihre Datenschutzrechte hängen von Ihrem Wohnort ab und können Auskunft, Berichtigung oder Löschung umfassen. Bei Fragen oder Anliegen kontaktieren Sie den Salon über die Angaben auf dieser Website oder in Ihrer Buchungsbestätigung. Der Salon kann nähere Informationen zu seiner konkreten Datenverarbeitung geben."),
                template("cookies", "Cookie Policy",
                        "This website and its booking features may use cookies or similar browser storage to operate, remember your choices and protect the service. Optional analytics or marketing technologies may be used where enabled and where required consent has been obtained. You can manage cookies in your browser and, where available, through the website’s cookie settings. Blocking essential storage may affect some features. Contact the salon using the details on this website with questions. The technologies used may change as the salon updates its website and services.",
                        "Denne hjemmeside og dens bookingfunktioner kan bruge cookies eller lignende browserlagring til at fungere, huske dine valg og beskytte tjenesten. Valgfri analyse- eller markedsføringsteknologier kan bruges, når salonen har aktiveret dem, og nødvendigt samtykke er indhentet. Du kan administrere cookies i din browser og, hvis muligt, via hjemmesidens cookieindstillinger. Blokering af nødvendig lagring kan påvirke nogle funktioner. Kontakt salonen via oplysningerne på hjemmesiden, hvis du har spørgsmål. Teknologierne kan ændres, når salonen opdaterer hjemmesiden og sine tjenester.",
                        "Den här webbplatsen och dess bokningsfunktioner kan använda kakor eller liknande lagring i webbläsaren för att fungera, komma ihåg dina val och skydda tjänsten. Valfria analys- eller marknadsföringstekniker kan användas när salongen har aktiverat dem och nödvändigt samtycke har inhämtats. Du kan hantera kakor i webbläsaren och, om det finns, via webbplatsens cookieinställningar. Om du blockerar nödvändig lagring kan vissa funktioner påverkas. Kontakta salongen via uppgifterna på webbplatsen om du har frågor. Teknikerna kan ändras när salongen uppdaterar webbplatsen och sina tjänster.",
                        "Dette nettstedet og bestillingsfunksjonene kan bruke informasjonskapsler eller lignende lagring i nettleseren for å fungere, huske valgene dine og beskytte tjenesten. Valgfrie analyse- eller markedsføringsteknologier kan brukes når salongen har aktivert dem og nødvendig samtykke er innhentet. Du kan administrere informasjonskapsler i nettleseren og, hvis tilgjengelig, via nettstedets innstillinger for informasjonskapsler. Blokkering av nødvendig lagring kan påvirke enkelte funksjoner. Kontakt salongen via opplysningene på nettstedet hvis du har spørsmål. Teknologiene kan endres når salongen oppdaterer nettstedet og tjenestene sine.",
                        "Ce site et ses fonctions de réservation peuvent utiliser des cookies ou un stockage similaire dans le navigateur pour fonctionner, mémoriser vos choix et protéger le service. Des technologies facultatives d’analyse ou de marketing peuvent être utilisées si le salon les active et si le consentement requis a été obtenu. Vous pouvez gérer les cookies dans votre navigateur et, si cette option existe, dans les paramètres du site. Le blocage du stockage essentiel peut affecter certaines fonctions. Pour toute question, contactez le salon aux coordonnées indiquées sur ce site. Les technologies utilisées peuvent évoluer avec les mises à jour du site et des services du salon.",
                        "Diese Website und ihre Buchungsfunktionen können Cookies oder einen ähnlichen Browserspeicher verwenden, damit sie funktionieren, Ihre Auswahl speichern und den Dienst schützen. Optionale Analyse- oder Marketingtechnologien können eingesetzt werden, wenn der Salon sie aktiviert hat und eine erforderliche Einwilligung vorliegt. Sie können Cookies in Ihrem Browser und, sofern verfügbar, in den Cookie-Einstellungen der Website verwalten. Das Blockieren notwendiger Speicherung kann einige Funktionen beeinträchtigen. Bei Fragen kontaktieren Sie den Salon über die Angaben auf dieser Website. Die eingesetzten Technologien können sich mit Aktualisierungen der Website und der Dienste ändern."),
                template("terms", "Terms and Conditions",
                        "These terms apply to services and, where offered, products provided by the salon identified on this website. Service descriptions, availability and prices are shown before you confirm a booking or purchase. Bookings are subject to availability and confirmation. Please review the Booking Policy for appointment changes and the Sales Policy for product purchases. Contact the salon using the details on this website or your confirmation if you have a question. Nothing in these terms limits consumer rights or legal protections that cannot be excluded or restricted. Mandatory rules that apply to you take precedence.",
                        "Disse vilkår gælder for ydelser og, hvor det tilbydes, produkter fra salonen, der er angivet på denne hjemmeside. Beskrivelser, tilgængelighed og priser vises, før du bekræfter en booking eller et køb. Bookinger afhænger af tilgængelighed og bekræftelse. Se Bookingpolitik for ændringer af aftaler og Salgspolitik for produktkøb. Kontakt salonen via oplysningerne på hjemmesiden eller i din bekræftelse, hvis du har spørgsmål. Intet i disse vilkår begrænser forbrugerrettigheder eller juridisk beskyttelse, som ikke lovligt kan fraviges. Ufravigelige regler, der gælder for dig, har forrang.",
                        "Dessa villkor gäller för tjänster och, där det erbjuds, produkter från salongen som anges på denna webbplats. Beskrivningar, tillgänglighet och priser visas innan du bekräftar en bokning eller ett köp. Bokningar beror på tillgänglighet och bekräftelse. Läs bokningspolicyn om ändringar av tider och försäljningspolicyn om produktköp. Kontakta salongen via uppgifterna på webbplatsen eller i din bekräftelse om du har frågor. Inget i dessa villkor begränsar konsumenträttigheter eller rättsligt skydd som inte får begränsas. Tvingande regler som gäller för dig har företräde.",
                        "Disse vilkårene gjelder for tjenester og, når det tilbys, produkter fra salongen som er angitt på dette nettstedet. Beskrivelser, tilgjengelighet og priser vises før du bekrefter en bestilling eller et kjøp. Bestillinger avhenger av tilgjengelighet og bekreftelse. Se bestillingsvilkårene for endring av avtaler og salgsvilkårene for produktkjøp. Kontakt salongen via opplysningene på nettstedet eller i bekreftelsen hvis du har spørsmål. Ingenting i disse vilkårene begrenser forbrukerrettigheter eller juridisk vern som ikke lovlig kan begrenses. Ufravikelige regler som gjelder for deg, går foran.",
                        "Les présentes conditions s’appliquent aux services et, le cas échéant, aux produits proposés par le salon identifié sur ce site. Les descriptions, disponibilités et prix sont indiqués avant la confirmation d’une réservation ou d’un achat. Les réservations sont soumises à disponibilité et confirmation. Consultez la politique de réservation pour les changements de rendez-vous et la politique de vente pour les achats de produits. Pour toute question, contactez le salon aux coordonnées de ce site ou de votre confirmation. Aucune disposition ne limite les droits des consommateurs ou protections légales qui ne peuvent être écartés. Les règles impératives qui vous sont applicables prévalent.",
                        "Diese Bedingungen gelten für Dienstleistungen und, sofern angeboten, Produkte des auf dieser Website genannten Salons. Beschreibungen, Verfügbarkeit und Preise werden angezeigt, bevor Sie eine Buchung oder einen Kauf bestätigen. Buchungen hängen von der Verfügbarkeit und Bestätigung ab. Informationen zu Terminänderungen finden Sie in der Buchungsrichtlinie, zu Produktkäufen in der Verkaufsrichtlinie. Bei Fragen kontaktieren Sie den Salon über die Angaben auf dieser Website oder in Ihrer Bestätigung. Diese Bedingungen schränken keine Verbraucherrechte oder gesetzlichen Schutzbestimmungen ein, auf die nicht verzichtet werden kann. Zwingende Vorschriften, die für Sie gelten, haben Vorrang."),
                template("booking", "Booking Policy",
                        "Choose from the services, staff, dates and times shown as available. Review the service description and price before confirming. Your booking is confirmed when you receive confirmation from the salon. To change or cancel, contact the salon using the details in your confirmation as soon as possible. Any notice period, deposit or cancellation charge that applies should be shown before you confirm. If you may arrive late or have a question about preparing for a service, contact the salon in advance. If the salon changes or cancels your appointment, it will contact you and explain the available options. Your legal cancellation rights continue to apply.",
                        "Vælg mellem de ydelser, medarbejdere, datoer og tidspunkter, der vises som ledige. Gennemgå ydelsens beskrivelse og pris, før du bekræfter. Din booking er bekræftet, når du modtager en bekræftelse fra salonen. Kontakt salonen via oplysningerne i bekræftelsen hurtigst muligt, hvis du vil ændre eller aflyse. Eventuelt varsel, depositum eller afbestillingsgebyr skal vises, før du bekræfter. Kontakt salonen på forhånd, hvis du bliver forsinket eller har spørgsmål til forberedelse. Hvis salonen ændrer eller aflyser din aftale, kontakter den dig og forklarer mulighederne. Dine lovbestemte afbestillingsrettigheder gælder fortsat.",
                        "Välj bland de tjänster, medarbetare, datum och tider som visas som tillgängliga. Läs tjänstebeskrivningen och priset innan du bekräftar. Bokningen är bekräftad när du får en bekräftelse från salongen. Kontakta salongen via uppgifterna i bekräftelsen så snart som möjligt om du vill ändra eller avboka. Eventuell tidsfrist, deposition eller avbokningsavgift ska visas innan du bekräftar. Kontakta salongen i förväg om du kan bli sen eller undrar hur du ska förbereda dig. Om salongen ändrar eller avbokar din tid kontaktar den dig och förklarar alternativen. Dina lagstadgade avbokningsrättigheter gäller fortfarande.",
                        "Velg blant tjenestene, medarbeiderne, datoene og tidene som vises som ledige. Les tjenestebeskrivelsen og prisen før du bekrefter. Bestillingen er bekreftet når du mottar en bekreftelse fra salongen. Kontakt salongen via opplysningene i bekreftelsen så snart som mulig hvis du vil endre eller avbestille. Eventuell frist, depositum eller avbestillingsavgift skal vises før du bekrefter. Kontakt salongen på forhånd hvis du kan bli forsinket eller lurer på hvordan du skal forberede deg. Hvis salongen endrer eller avbestiller timen, kontakter den deg og forklarer alternativene. Lovfestede avbestillingsrettigheter gjelder fortsatt.",
                        "Choisissez parmi les services, membres du personnel, dates et horaires indiqués comme disponibles. Consultez la description et le prix avant de confirmer. Votre réservation est confirmée lorsque vous recevez une confirmation du salon. Pour la modifier ou l’annuler, contactez le salon dès que possible aux coordonnées figurant dans la confirmation. Tout délai, acompte ou frais d’annulation applicable doit être indiqué avant la confirmation. Contactez le salon à l’avance en cas de retard ou de question sur la préparation au service. Si le salon modifie ou annule votre rendez-vous, il vous contactera pour vous présenter les options disponibles. Vos droits légaux d’annulation restent applicables.",
                        "Wählen Sie aus den als verfügbar angezeigten Dienstleistungen, Mitarbeitenden, Terminen und Uhrzeiten. Prüfen Sie Beschreibung und Preis, bevor Sie bestätigen. Ihre Buchung ist bestätigt, sobald Sie eine Bestätigung des Salons erhalten. Wenden Sie sich so bald wie möglich über die Angaben in der Bestätigung an den Salon, wenn Sie ändern oder stornieren möchten. Eine geltende Frist, Anzahlung oder Stornogebühr muss vor der Bestätigung angezeigt werden. Kontaktieren Sie den Salon vorab, wenn Sie sich verspäten könnten oder Fragen zur Vorbereitung haben. Ändert oder storniert der Salon Ihren Termin, informiert er Sie über die verfügbaren Möglichkeiten. Ihre gesetzlichen Stornierungsrechte bleiben bestehen."),
                template("refunds", "Refund Policy",
                        "If you have a concern about a salon service or a product purchased from the salon, contact the salon using the details on this website or your booking or purchase confirmation. Include the appointment or order details and describe the issue so the salon can review it and explain the next steps. Refunds, cancellations, returns and other remedies depend on the service or product and the circumstances. Any rights provided by applicable consumer law remain in place, including rights relating to faulty or misdescribed products and services that do not meet legal requirements. The salon will explain the resolution available for your case.",
                        "Kontakt salonen via oplysningerne på hjemmesiden eller din booking- eller købskvittering, hvis du har et problem med en ydelse eller et produkt købt hos salonen. Oplys aftalen eller ordren, og beskriv problemet, så salonen kan undersøge sagen og forklare næste skridt. Refusion, aflysning, returnering og andre løsninger afhænger af ydelsen eller produktet og omstændighederne. Dine rettigheder efter gældende forbrugerlovgivning gælder fortsat, herunder rettigheder ved fejlbehæftede eller forkert beskrevne produkter og ydelser, der ikke opfylder lovkrav. Salonen forklarer, hvilken løsning der gælder i din sag.",
                        "Kontakta salongen via uppgifterna på webbplatsen eller i din boknings- eller köpbekräftelse om du har synpunkter på en tjänst eller en produkt som köpts hos salongen. Ange bokningen eller ordern och beskriv problemet så att salongen kan granska det och förklara nästa steg. Återbetalning, avbokning, retur och andra åtgärder beror på tjänsten eller produkten och omständigheterna. Dina rättigheter enligt tillämplig konsumentlagstiftning gäller fortfarande, inklusive rättigheter vid felaktiga eller felbeskrivna produkter och tjänster som inte uppfyller lagkrav. Salongen förklarar vilken lösning som gäller i ditt fall.",
                        "Kontakt salongen via opplysningene på nettstedet eller i bestillings- eller kjøpsbekreftelsen hvis du har et problem med en tjeneste eller et produkt kjøpt hos salongen. Oppgi bestillingen eller ordren og beskriv problemet, slik at salongen kan undersøke saken og forklare neste steg. Refusjon, avbestilling, retur og andre løsninger avhenger av tjenesten eller produktet og omstendighetene. Rettighetene dine etter gjeldende forbrukerlovgivning gjelder fortsatt, blant annet ved mangelfulle eller feilbeskrevne produkter og tjenester som ikke oppfyller lovkrav. Salongen forklarer hvilken løsning som gjelder i din sak.",
                        "Si vous avez une question ou un problème concernant un service du salon ou un produit acheté auprès de celui-ci, contactez le salon aux coordonnées de ce site ou de votre confirmation de réservation ou d’achat. Indiquez le rendez-vous ou la commande et décrivez le problème afin que le salon puisse l’examiner et vous expliquer la suite. Les remboursements, annulations, retours et autres recours dépendent du service ou du produit et des circonstances. Vos droits prévus par le droit de la consommation applicable restent inchangés, notamment pour les produits défectueux ou non conformes et les services qui ne respectent pas les exigences légales. Le salon vous expliquera la solution applicable à votre situation.",
                        "Wenn Sie ein Anliegen zu einer Salonleistung oder einem dort gekauften Produkt haben, kontaktieren Sie den Salon über die Angaben auf dieser Website oder in Ihrer Buchungs- oder Kaufbestätigung. Nennen Sie den Termin oder die Bestellung und beschreiben Sie das Problem, damit der Salon es prüfen und die nächsten Schritte erläutern kann. Rückerstattungen, Stornierungen, Rückgaben und andere Abhilfen hängen von der Leistung oder dem Produkt und den Umständen ab. Ihre Rechte nach geltendem Verbraucherrecht bleiben bestehen, auch bei mangelhaften oder falsch beschriebenen Produkten und Leistungen, die gesetzliche Anforderungen nicht erfüllen. Der Salon erläutert die für Ihren Fall verfügbare Lösung."),
                template("sales", "Sales Policy",
                        "Where the salon offers products for sale, descriptions, availability and prices are provided before purchase. Any applicable taxes, delivery charges or other costs will be shown before you place an order. Orders depend on availability and confirmation. Collection or delivery arrangements, where offered, will be explained at purchase. If an item is unavailable or an order cannot be fulfilled, the salon will contact you and explain the options. Contact the salon using the details on this website or your purchase confirmation with any questions. Your legal rights concerning faulty, misdescribed or non-conforming products are not affected.",
                        "Når salonen sælger produkter, vises beskrivelser, tilgængelighed og priser før købet. Eventuelle skatter, leveringsgebyrer eller andre omkostninger vises, før du afgiver en ordre. Ordrer afhænger af tilgængelighed og bekræftelse. Afhentning eller levering forklares ved købet, hvis det tilbydes. Hvis en vare ikke er tilgængelig, eller en ordre ikke kan gennemføres, kontakter salonen dig og forklarer mulighederne. Kontakt salonen via oplysningerne på hjemmesiden eller din købskvittering, hvis du har spørgsmål. Dine lovbestemte rettigheder ved fejlbehæftede, forkert beskrevne eller mangelfulde produkter påvirkes ikke.",
                        "När salongen säljer produkter visas beskrivningar, tillgänglighet och priser före köpet. Eventuella skatter, leveransavgifter och andra kostnader anges innan du lägger en beställning. Beställningar beror på tillgänglighet och bekräftelse. Information om hämtning eller leverans lämnas vid köpet när detta erbjuds. Om en vara inte finns tillgänglig eller en beställning inte kan fullföljas kontaktar salongen dig och förklarar alternativen. Kontakta salongen via uppgifterna på webbplatsen eller i ditt köpbesked om du har frågor. Dina lagstadgade rättigheter för felaktiga, felbeskrivna eller bristfälliga produkter påverkas inte.",
                        "Når salongen selger produkter, vises beskrivelser, tilgjengelighet og priser før kjøpet. Eventuelle skatter, leveringsgebyrer og andre kostnader oppgis før du legger inn en bestilling. Bestillinger avhenger av tilgjengelighet og bekreftelse. Informasjon om henting eller levering gis ved kjøpet når dette tilbys. Hvis en vare ikke er tilgjengelig eller en bestilling ikke kan gjennomføres, kontakter salongen deg og forklarer alternativene. Kontakt salongen via opplysningene på nettstedet eller i kjøpsbekreftelsen hvis du har spørsmål. Lovfestede rettigheter ved mangelfulle, feilbeskrevne eller defekte produkter påvirkes ikke.",
                        "Lorsque le salon vend des produits, leur description, leur disponibilité et leur prix sont indiqués avant l’achat. Les taxes, frais de livraison et autres coûts éventuels sont précisés avant la commande. Les commandes dépendent de la disponibilité et de la confirmation. Les modalités de retrait ou de livraison, lorsqu’elles sont proposées, sont communiquées lors de l’achat. Si un article est indisponible ou si une commande ne peut être honorée, le salon vous contactera pour vous présenter les options. Pour toute question, contactez le salon aux coordonnées de ce site ou de votre confirmation d’achat. Vos droits légaux concernant les produits défectueux ou non conformes restent inchangés.",
                        "Wenn der Salon Produkte verkauft, werden Beschreibung, Verfügbarkeit und Preis vor dem Kauf angezeigt. Etwaige Steuern, Lieferkosten und sonstige Gebühren werden vor der Bestellung genannt. Bestellungen hängen von Verfügbarkeit und Bestätigung ab. Informationen zu Abholung oder Lieferung werden beim Kauf mitgeteilt, sofern dies angeboten wird. Ist ein Artikel nicht verfügbar oder kann eine Bestellung nicht ausgeführt werden, informiert Sie der Salon über die Möglichkeiten. Bei Fragen kontaktieren Sie den Salon über die Angaben auf dieser Website oder in Ihrer Kaufbestätigung. Ihre gesetzlichen Rechte bei mangelhaften oder falsch beschriebenen Produkten bleiben unberührt."));
    }

    private SalonPolicy template(String key, String title, String en, String da, String sv, String nb, String fr, String de) {
        return new SalonPolicy(key, title, true, true, true, "DEFAULT", "en",
                Map.of("en", en, "da", da, "sv", sv, "nb", nb, "fr", fr, "de", de));
    }

    List<SalonPolicy> editor(UUID salonId) {
        var stored = jdbc.sql("SELECT draft_document FROM salon_policy_document WHERE salon_id = :id")
                .param("id", salonId).query(String.class).list();
        var result = new java.util.LinkedHashMap<String, SalonPolicy>();
        var defaults = defaults();
        defaults.forEach(policy -> result.put(policy.key(), policy));
        var defaultByKey = defaults.stream().collect(java.util.stream.Collectors.toMap(SalonPolicy::key, policy -> policy));
        stored.stream().map(this::decode).forEach(policy -> {
            // Refresh untouched built-in copy as the starter wording improves, while preserving
            // each salon's title, visibility selections and any text marked CUSTOM.
            var current = policy.source().equals("DEFAULT") && defaultByKey.containsKey(policy.key())
                    ? new SalonPolicy(policy.key(), policy.title(), policy.enabled(), policy.website(), policy.booking(),
                    policy.source(), defaultByKey.get(policy.key()).defaultLanguage(), defaultByKey.get(policy.key()).translations())
                    : policy;
            result.put(current.key(), current);
        });
        return List.copyOf(result.values());
    }

    List<SalonPolicy> published(UUID salonId, String placement) {
        String field = "website".equals(placement) ? "website" : "booking";
        var resolved = new java.util.LinkedHashMap<String, SalonPolicy>();
        defaults().forEach(policy -> resolved.put(policy.key(), policy));
        jdbc.sql("SELECT published_document FROM salon_policy_document WHERE salon_id = :id AND published_document IS NOT NULL")
                .param("id", salonId).query(String.class).list().stream().map(this::decode)
                .forEach(policy -> resolved.put(policy.key(), policy));
        return resolved.values().stream()
                .filter(policy -> policy.enabled() && ("website".equals(field) ? policy.website() : policy.booking()))
                .toList();
    }

    @Transactional
    List<SalonPolicy> save(UUID salonId, List<SalonPolicy> policies) {
        if (policies == null || policies.size() > 100 || policies.stream().map(SalonPolicy::key).distinct().count() != policies.size()) {
            throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.BAD_REQUEST, "Invalid policy list.");
        }
        for (var policy : policies) {
            jdbc.sql("""
                    INSERT INTO salon_policy_document (salon_id, policy_key, draft_document, updated_at)
                    VALUES (:id, :key, :document, now())
                    ON CONFLICT (salon_id, policy_key) DO UPDATE SET draft_document = EXCLUDED.draft_document, updated_at = now()
                    """).param("id", salonId).param("key", policy.key()).param("document", encode(policy)).update();
        }
        return editor(salonId);
    }

    @Transactional
    List<SalonPolicy> publish(UUID salonId) {
        jdbc.sql("UPDATE salon_policy_document SET published_document = draft_document, published_at = now() WHERE salon_id = :id")
                .param("id", salonId).update();
        return editor(salonId);
    }

    private String encode(SalonPolicy policy) {
        try { return json.writeValueAsString(policy); }
        catch (JsonProcessingException e) { throw new IllegalStateException("Could not save salon policy", e); }
    }

    private SalonPolicy decode(String document) {
        try { return json.readValue(document, SalonPolicy.class); }
        catch (JsonProcessingException e) { throw new IllegalStateException("Could not read salon policy", e); }
    }
}
